name: Run Web Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install a Stable Version of Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Install ChromeDriver for Stable Chrome Version
      run: |
        # Manually specify a stable version of ChromeDriver that is known to be compatible
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip
        chromedriver --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas

    - name: Modify script for headless mode
      run: |
        sed -i 's/webdriver.Chrome()/webdriver.Chrome(options=options)/' scripts/reference_scrape.py
        sed -i '/driver = webdriver.Chrome()/a options = webdriver.ChromeOptions() \noptions.add_argument("--headless") \noptions.add_argument("--no-sandbox") \noptions.add_argument("--disable-dev-shm-usage")' scripts/reference_scrape.py

    - name: Run web scraping script in headless mode
      run: |
        python scripts/reference_scrape.py

    - name: Commit CSV files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.csv
        git commit -m "Updated CSV files from scraper"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
