name: Scrape

on:
  workflow_dispatch:
  [push]:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight, adjust as needed

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Specify your Python version

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure requirements.txt is up-to-date

      # Run the scraping script
      - name: Run scraping script
        run: python reference_scrape_local.py

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Update scraped data"
          git push
        env:
          # This is to allow GitHub actions to push changes to the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
