name: Selenium Scrape

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your desired Python version

      - name: Install Dependencies
        run: |
          pip install selenium pandas

      - name: Install ChromeDriver with Retry
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROME_VERSION=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          for i in {1..5}; do
              wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && break || sleep 15;
          done
          unzip chromedriver_linux64.zip -d $HOME/chromedriver/
          sudo chmod +x $HOME/chromedriver/chromedriver
          echo "$HOME/chromedriver" >> $GITHUB_PATH




      - name: Run Selenium Script
        env:
          DISPLAY: ':99.0'
        run: |
          sudo Xvfb :99 -ac &
          python scripts/reference_scrape.py
