name: Selenium Scrape

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your desired Python version

      - name: Install Dependencies
        run: |
          pip install selenium pandas

      - name: Install Latest ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/bin/
          sudo chmod +x /usr/bin/chromedriver

      - name: Run Selenium Script
        env:
          DISPLAY: ':99.0'
        run: |
          sudo Xvfb :99 -ac &
          python scripts/reference_scrape.py
